src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/config/ResourceServerConfiguration.kt

Forgot disable security on the API

Add dlq retry cron job (remove spring sec on that one API)

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/listeners/PrisonerDomainEventsListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/UpdateQueueService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/PrisonVisitsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsMappingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/helpers/Messages.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesMappingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/listeners/PrisonerDomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/PrisonVisitsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsMappingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/MappingMockServer.kt

SDI-360 Update Nomis from incentive creation domain event

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/listeners/PrisonerDomainEventsListener.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/listeners/PrisonerDomainEventsListenerTest.kt

SDI-401 SQS Alerts not triggering for hmpps-nomis-to-prisoner-migration project

---

activities-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/integration/ActivityToNomisTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt

SDI-505 Handle activities.activity.created event

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingDomainEventListener.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/integration/SqsIntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsToNomisTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt

Test for happy path 
TODO
* Exception handling
* Retry

SDI-538 create adjustment happy path

---

activities-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivityToNomisTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiServiceTest.kt

SDI-507 Handle activities.prisoner.allocated event

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/integration/LocalStackContainer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/integration/SqsIntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsToNomisTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/MappingMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt

TODO:
- Exception paths
- Mapping doesn't exist path

SDI-537 Happy path for update adjustment

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/HmppsPrisonerToNomisUpdate.kt
src/main/resources/application.yml

Like this: https://www.amitph.com/spring-boot-startup-monitoring/#enable_applicationstartup_metrics

SDI-632 Gather startup metrics

---

activities-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivityToNomisIntTest.kt

Now with non-nullable Nomis incentive level codes

SDI-610 update to latest activities api

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingRetryQueueService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/RetryQueueService.kt

First step to make mapping retry generic

SDIT-642 Use generic queue sender

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesUpdateQueueService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/SynchronisationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesDomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivityToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/helpers/Messages.kt

Use shared  Listener and Mapping retry

SDIT-642 Activities refactor

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/health/HealthCheck.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesDomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesMappingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsMappingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesDomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesMappingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentMappingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsDomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsMappingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsServiceTest.kt

* no blocking calls at webClient
* wrap tests in `runTest`
* change assertThrownBy to assertThrows that supports suspend

SDIT-642 Everything now reactive or suspend

---

activities-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/main/resources/application-localstack.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/AppointmentsApiMockServer.kt
src/test/resources/application-test.yml

Tweaks needed now that real event and api endpoint is available

SDI-639 Create a 'create-appointment' handler

---

activities-api-docs.json
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesDomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivityToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationsIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendanceServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendancesIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesServiceTest.kt

Nothing functional has changed. I've split the handlers for different message types into separate services and the same for the unit and integration tests. And tidied up some names in tests for consistency.

SDIT-743 updates and refactor

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendanceService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendanceServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesServiceTest.kt

Standardise telemetry keys coming from DPS (activities) / Nomis. Also should use the same keys as the [API](https://github.com/ministryofjustice/hmpps-nomis-prisoner-api/pull/277).

SDIT-422 Standardise telemetry

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesConfiguration.kt

...to make use of property `spring.codec.max-in-memory-size` and prevent a `DataBufferLimitException`

SDIT-845 Use the Spring web client builder 

---

openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendanceService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesMappingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivityToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationsIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendanceServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendancesIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/MappingMockServer.kt

See the [last commit](https://github.com/ministryofjustice/hmpps-prisoner-to-nomis-update/pull/311/commits/4d0e6d5cc89853a7ee5f77a2a426be101402c3d0) to avoid noise from an OpenAPI spec update and refactoring.

SDIT-838 Send Nomis course schedule ids for updates

---

openapi-specs/activities-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationsIntTest.kt

As the client is currentlybroke 😢

SDIT-838 Update to latest activities API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt

SDIT-855 Appointments un-cancel event

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsServiceTest.kt

SDIT-856 Appointments comments syncing

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivityToNomisIntTest.kt

Activities will soon return only recent and future scheduled instances instead of the full history which will become huge over time. This change maintains the Nomis/Activities schedule mappings in that scenario.

SDIT-906 Handle partial scheduled instance response from Activities

---

helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjustments/AdjudicationsDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjustments/AdjudicationsService.kt
src/main/resources/application-dev.yml
src/main/resources/application-localstack.yml
src/main/resources/application.yml
src/test/resources/application-test.yml

* SQS Subscription has been created in T3
* Client credentials has been created in T3

SDIT-969 Skeleton handler for adjudication events

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/helpers/WebClientHelpers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/SynchronisationHelpers.kt

Allow for no existing mapping data

SDIT-936 Duplicate mapping not detected

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsToNomisIntTest.kt

SDIT-995 Add Non-association create sync service to nomis

---

openapi-specs/non-associations-api-docs.json

update non-association API swagger json

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-incentives-cronjob.yaml
helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-non-associations-cronjob.yaml
helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/config/ResourceServerConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/SynchronisationHelpers.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsReconciliationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NonAssociationsApiMockServer.kt
src/test/resources/application-test.yml

Initial PR for report with these limitations:
- only compares 2 fields of the NA so far
- only loops through NAs from Nomis; does not find extra NAs only in the new service

SDIT-1096 Non-association Reconciliation process

---

helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml

Make cronjob name wildcard more specific

SDIT-1119 False alert for long-running reconciliation cronjob

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/PunishmentsMappingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/PunishmentsMappingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/PunishmentsToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/AdjudicationsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/MappingMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt

TODO
1. Consecutive awards
2. Better understand and testing on mapping from DPS to NOMIS

SDIT-1138 Create punishment implementation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/PunishmentsToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt

TODO
* since quash and update are so similar should be able to refactor so shares code better

SDIT-1191 unquash awards processing

---

README.md
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesDataRepairResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesDataRepairResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/IncentivesApiMockServer.kt

Required in the very rare scenario when to Incentives are added in quick succession and their is a network issue

SDIT-1265 Add repair endpoint to synchronise current incentive level to NOMIS

---

openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingReconciliationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/SentencingAdjustmentsApiMockServer.kt

* also add convenience extension for WireMock to supply objects for bodies

SDIT-1264 Use real NOMIS adjustment DTOs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/HearingsMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/PunishmentsMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/helpers/WebClientHelpers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsMappingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsApiServiceTest.kt

422 error from DPS adjustments means prisoner has no active sentence so can't return adjustments. For now we will treat these as no adjustments and see how that pans out - though I guess we will just skip them eventually.

SDIT-1264 Catch 422 adjustments errors 

---

openapi-specs/adjudications-api-docs.json
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsReconciliationServiceTest.kt

will require DPA fix in New Year

SDIT-1326 Manual fix for missing CORRUPTED enum - 

---

openapi-specs/sentencing-adjustments-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsApiService.kt

CORRUPTED status was replaced with INVALID_OUTCOME,INVALID_SUSPENDED,INVALID_ADA
Also removed the obvious status before a punishment can exist

SDIT-1453 Correct status for adjudication reconciliation GET

---

helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

SDIT-1497 To Nomis sync create and delete

---

openapi-specs/locations-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsApiServiceTest.kt

Fix location attributes openapi issue,
parent id fix

SDIT-1497 To Nomis sync updates

---

openapi-specs/nomis-mapping-service-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtCasesToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/CourtSentencingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/MappingMockServer.kt

Add in court appearance mapping as part of court case mapping creation

Sdit 1510 court as

---

build.gradle.kts
openapi-specs/alerts-api-docs.json
openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/helpers/SpringAPIServiceTest.kt

* Call it prior to creating an alert in NOMIS

SDIT-1573 Integration for DPS getAlerts API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/Transformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsToNomisIntTest.kt

* TODO handle mapping create failures

SDIT-1573 Happy Path for Alerts created in DPS and NOMIS

---

openapi-specs/alerts-api-docs.json
openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/Transformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsToNomisIntTest.kt

Future changes might include:
* Reduce set of items that can be updated
* Comments might be a list of comments for each update

SDIT-1585 Handle the prisoner-alerts.alert-updated DPS domain event

---

openapi-specs/locations-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsService.kt
src/main/resources/application-localstack.yml
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsToNomisIntTest.kt
src/test/resources/application-test.yml

Update to breaking change in locations api

SDIT-1497 To Nomis locations sync updates

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsToNomisIntTest.kt

Fix for occurredAt datetime with BST offset

SDIT-1497 To Nomis locations sync updates - date fix

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsReconciliationServiceTest.kt

When the latest booking does not match and there are missing adjudications on the current booking due to a merge, this will now include adjudications from the previous merged booking and recalculate.
This happens for a handful of the active prisoners
This is needed until NOMIS changes how merges from Adjudications are processed.

SDIT-1625 Extend reconciliation to look at merged bookings

---

openapi-specs/locations-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsReconciliationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsToNomisIntTest.kt

Add details of history discrepancies

SDIT-1619 Locations reconciliation

---

openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsReconciliationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingReconciliationServiceTest.kt

This required for reconciliation.
Also fixed incoming swagger changes for tests from nomis API

SDIT-1730 Integration for NOMIS and DPS API to get all active alerts

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-alerts-cronjob.yaml
helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/config/ResourceServerConfiguration.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsResourceIntTest.kt
src/test/resources/application-test.yml

CRON job added but disabled until we are ready

SDIT-1730 Reconciliation processing for alerts

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsResourceIntTest.kt

NOMIS has a small number of alerts that should be inactive but are not:
* Alerts past their expiry dates
* Alerts not started These will be logged but not considered a mismatch until the DPS decides what to do with these

SDIT-1730 Ignore alerts that should be inactive in NOMIS

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsReferenceDataService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsReferenceDataToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsToNomisIntTest.kt

Call-back to DPS API and check the state for reactivate/deactivate

SDIT-1785 Alert reference data skeleton

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsReferenceDataService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsReferenceDataToNomisIntTest.kt

For each event call the appropriate NOMIS API

SDIT-1785 Handle 8 alert ref data events

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/activities-tidy-mappings-cronjob.yaml

SDIT-1803 Kubernetes expects booleans for suspend, not strings

---

build.gradle.kts
openapi-specs/casenotes-api-docs.json
openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesMappingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesNomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesMappingApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesNomisApiServiceTest.kt

Create the Nomis and Mapping APIs

SDIT-1854 Casenotes sync to nomis

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/RetryApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsReconciliationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingReconciliationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiServiceTest.kt

Adding more endpoints and more detailed logging

SDIT-1917 Introduce Mono retry feature on some endpoints used by reconciliation

---

openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesRetryQueueService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/Transformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesNomisApiServiceTest.kt

SDIT-1854 Casenotes sync to nomis part 3

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsReconciliationService.kt

SDIT-1896 AppInsights span per reconciliation check

---

src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt

Remove some noise from the next PR (which will be big)

SDIT-1829 Small refactor prior to adding new tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesToNomisIntTest.kt

dps-only casenotes should not be synced

SDIT-1854 Casenotes sync to nomis - ignore dps-only

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsReconciliationService.kt
src/main/resources/application-localstack.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsReconciliationServiceTest.kt

Also add check for parent locations

SDIT-2038 locations reconciliation - ignore permanently deactivated locations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt

SDIT-2146 Add ability for reconciliation to check active prisoners only - network retries

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-casenotes-cronjob.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesReconciliationServiceTest.kt

Revise casenotes schedule temporarily to be every day, and ignore a known discrepancy

SDIT-1855 Casenotes reconciliation - schedule and condition

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
openapi-specs/contact-person-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiServiceTest.kt

TODO:
1) Add real NOMIS endpoint
2) Add real mapping GET endpoint
3) Do integration

SDIT-2119 Skeleton integration for contacts-api.contact.created

---

helm_deploy/values-dev.yaml
openapi-specs/contact-person-api-docs.json
openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonRetryQueueService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonToNomisIntTest.kt
src/test/resources/application-test.yml

TODO:
* Failure scenarios
* DPS needs source attribute

SDIT-2119 Baisc integration for contacts-api.contact.created

---

src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonToNomisIntTest.kt

SDIT-2119 Integration for contacts-api.contact.created

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDomainEventListener.kt

Give source a default value while waiting for DPS to change

SDIT-2235 Process "contacts-api.prisoner-contact.created"

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendanceService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendancesIntTest.kt

There are various reasons why an attendance might not exist in NOMIS but delete be requested by DPS. Having investigated these for at least year I've come to the conclusion that it doesn't matter - nothing bad has ever come of a failed attendance delete and the we just end up deleting the failed event from the DLQ.

SDIT-2317 Ignore attendance delete failed if not found

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonToNomisIntTest.kt

Also contacts-api.contact-address-phone.created

SDIT-2297 contacts-api.contact-phone.created

---

openapi-specs/nomis-mapping-service-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesMappingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesMappingApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesReconciliationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesToNomisIntTest.kt

Reconciliation rewritten to be based on mappings

SDIT-2246 Add reconciliation report feature to check for MERGE casenotes and duplicates

---

openapi-specs/nomis-mapping-service-api-docs.json
openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonToNomisIntTest.kt
src/test/resources/application-test.yml

SDIT-2297 contacts-api.contact-identity.created

---

openapi-specs/contact-person-api-docs.json
openapi-specs/nomis-mapping-service-api-docs.json
openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiServiceTest.kt

SDIT-2297 contacts-api.prisoner-contact-restriction.created

---

openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonNomisApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonToNomisIntTest.kt
src/test/resources/application-test.yml

and contacts-api.prisoner-contact-restriction.updated

SDIT-2309 contacts-api.contact-restriction.updated

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt

Also some minor upgrades of NA web client retry config

SDIT-2347-Add-a-description-check-to-the-locations-reconciliation-2

---

openapi-specs/contact-person-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonMappingApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/contactperson/ContactPersonToNomisIntTest.kt

For each of the DPS deletes also delete the mapping
Also latest DPS OpenApi DTOs

SDIT-2285 Added mapping deletes

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-sentencing-cronjob.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingReconciliationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingResourceIntTest.kt

DPS has requested report includes the latest booking for all prisoners. Initial refactor to support this.
Also fixed some compile warnings

SDIT-2384 Prep-work for adjustments reconciliation

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-casenotes-cronjob.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesReconciliationServiceTest.kt

Also compare creationDateTime and adjust active recon job start time to 18:30

SDI-1855 Casenotes reconciliation tweaks

---

openapi-specs/nomis-sync-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesReconciliationServiceTest.kt

Take all usernames for the staff id into account

SDI-2481 Case notes reconciliation username check can fail

---

src/main/resources/application.yml

This reverts commit 84820bae179fda18af22bedc7dc89a26fb93cecb.

Revert "SDIT-2541 Increase max response size (#868)"

---

openapi-specs/nomis-mapping-service-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsDataRepairResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsDataRepairResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/AdjudicationsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/MappingMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt

This does the following:
* Deletes any existing mappings
* Creates the core adjudication and mappings
* Creates each hearing and mapping
* Creates each hearing outcome
* Creates each punishment and mapping

SDIT-2617 Adjudication repair endpoint.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingReconciliationService.kt

Switch to DPS effectiveDays which is what is sent to NOMIS

SDIT-2627 Ignore zero day sentence adjustments in reconciliation

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-contactperson-prisonercontact-cronjob.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationServiceTest.kt

SDIT-2628 Contact reconciliation

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-contactperson-personcontact-cronjob.yaml
helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml
openapi-specs/nomis-prisoner-api-docs.json
openapi-specs/personal-relationships-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/config/ResourceServerConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResourceIntTest.kt

* Plumbing for person version of reconciliation
* Does nothing more than iterate through every page of person Ids
* Integration with the check endpoints

SDIT-2628 Contact person reconciliation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsToNomisIntTest.kt

* Scenario is NOMIS apis hangs but delete succeeds
* migration picks up the delete event from NOMIS and deletes mapping
* endless retry loop since mapping is no long found even though record has been deleted

SDIT-2679 Ignore deleted adjustments when already deleted

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationServiceTest.kt

TODO
* restrictions
* related prisoners

SDIT-2373 Person/Contact reconciliation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResourceIntTest.kt

URL change so that it is not blocked by ingress rules

SDIT-2373 Endpoint to reconcile individual contact

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-casenotes-cronjob.yaml
helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-casenotes-full-cronjob.yaml

Adjust casenotes reconciliation job start time to 19:30

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/casenotes/CaseNotesReconciliationServiceTest.kt

Find DPS case note by contents, not by legacy id

SDIT-2704 Handle duplicate case notes from to-nomis sync - fix

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/HearingOutcomesToNomisIntTest.kt

Fixes issue for false positives on DLQ when a hearing and outcome are deleted in quick succession

SDIT-2708 Ignore deleted hearings for a deleted hearing outcome

---

openapi-specs/personal-relationships-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationServiceTest.kt

Reduce the three DPS calls to a single reconcile specific version

SDIT-2373 Use unified DPS contact reconciliation API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResourceIntTest.kt

SDIT-2373 Move Person reconciliation to use channels

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtCasesToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/CourtSentencingApiMockServer.kt

* Retrieves recall - though waiting for a new endpoint
TODO  update NOMIS

SDIT-2764 Recall inserted event integration

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtCasesToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt

TODO rework NOMIS request to accept multiple recall sentence types

SDIT-2764 Initial NOMIS Recall request

---

openapi-specs/court-sentencing-api-docs.json
openapi-specs/nomis-prisoner-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtCasesToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/CourtSentencingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt

* Call improved NOMIS API endpoint that passes all sentence types
* Call legacy version of /recall from DPS

SDIT-2764 Convert to Recall

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtCasesToNomisIntTest.kt
src/test/resources/application-test.yml

* Also refactored to reduce duplicate code
* TODO - create specific NOMIS API calls

SDIT-2783 Process recall.deleted

---

openapi-specs/nomis-prisoner-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingNomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtCasesToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/CourtSentencingApiMockServer.kt

Call the update or delete recall endpoint as appropriate since each version is slightly different

SDIT-2782 Recall updated/delete - nomis api call

---

openapi-specs/personal-relationships-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationServiceTest.kt

Reduces the number of calls to DPS by using a specific crafted reconcile endpoint
Also cleaned some IntelliJ warnings including grammar warnings

SDIT-2778 Switch to DPS Contacts reconcile endpoint

---

openapi-specs/nomis-mapping-service-api-docs.json
openapi-specs/nomis-prisoner-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtCaseMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingNomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtCasesToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/integration/SqsIntegrationTestBase.kt

A new recall will create a breach court hearing; these will be stored in mapping and used for later deletes and updates
TODO - clean up recall mappings after a recall delete

SDIT-2817 Set and Get breach appearance court Id for recalls

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonToNomisIntTest.kt

DPS now supports deleting contacts

SDIT-2881 Implement contacts-api.prisoner-contact.deleted

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-contactperson-prisonerrestriction-cronjob.yaml
openapi-specs/nomis-prisoner-api-docs.json
openapi-specs/personal-relationships-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/PrisonerReconciliationReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/PrisonerRestrictionsReconciliationResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiServiceTest.kt

TODO - actually checking of restrictions and page counts

SDIT-2945 Basic prisoner restrictions reconciliation

---

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-contactperson-prisonerrestriction-cronjob.yaml
helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/PrisonerRestrictionsReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/PrisonerRestrictionsReconciliationResourceIntTest.kt

SDIT-2945 Prisoner restrictions reconciliation counts

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/PrisonerRestrictionsReconciliationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/PrisonerRestrictionsReconciliationResourceIntTest.kt

SDIT-2945 Prisoner restrictions reconciliation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDomainEventListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonMappingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/PrisonerRestrictionsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonMappingApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/PrisonerRestrictionToNomisIntTest.kt
src/test/resources/application-test.yml

This version just ignores them all since we have no DPS sourced ones yet, there is no DPS UI to created restrictions

SDIT-2973 Prisoner restrictions sync

---

openapi-specs/nomis-mapping-service-api-docs.json
openapi-specs/nomis-prisoner-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonMappingApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonMappingApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonMappingApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiServiceTest.kt

SDIT-2973 Prisoner restrictions sync integration

---

helm_deploy/hmpps-prisoner-to-nomis-update/Chart.yaml
helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml

This reverts commit 12a7d60b2721bee9e6ed70c34f7919fd2308cf18.

Revert "SDIT-2804 Try the new style of Cronjob from the generic-service chart (#1580)"

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentMappingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsMappingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsReconciliationServiceTest.kt
src/test/resources/application-test.yml

extend date range
add api call retries

SDIT-2678-Appointment-reconciliation-2

---

build.gradle.kts
openapi-specs/locations-api-docs.json
openapi-specs/nomis-prisoner-api-docs.json
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/helpers/WebClientHelpers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsReconciliationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsReconciliationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsToNomisIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/LocationsApiMockServer.kt

internalMovementAllowed / tracking flag

SDIT-3040-New-location-field-needs-adding-to-sync

---

openapi-generator-ignore-visit-balance
openapi-specs/alerts-api-docs.json
openapi-specs/nomis-mapping-service-api-docs.json
openapi-specs/visit-balance-api-docs.json
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiMockServer.kt

Closes #1686
Closes #1685 
Closes #1684

SDIT-3089: 👽️ Update api docs and fix
