src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsDomainEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsUpdateQueueService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/helpers/Messages.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsDomainEventsListenerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsServiceTest.kt
What we lose:
1. Telemetry on failures - rely on DLQ and exceptions
2. Some telemetry attributes on a duplicate domain event (we don't bother reading a visit if it detected as a duplicate event so no times etc added to telemetry
=> SDIT-642 Use synchronise helper for visits create

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesDomainEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesUpdateQueueService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/helpers/Messages.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesDomainEventsListenerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/incentives/IncentivesServiceTest.kt
What we lose:
- Custom event when create fails, rely on DLQ and exception logging
=> SDIT-642 Use synchronise helper for incentives create

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt
* This prior to making other domain use the same techniques
* Consistent telemetry names
* Switch to use `runCatching`
=> SDIT-642 Make consistent telemetry naming and exception technique

openapi-specs/adjudications-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjustments/AdjudicationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationTransformationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/AdjudicationsApiMockServer.kt
DPS has moved from an Adjudication Number which was a Long to a charge number that is a String that might contain a charge sequence for NOMIS migrated adjudications.
For he create adjudication scenario the chargeNumber is the same as the adjudication number - it is just a string
=> SDIT-969 Fix removal of adjudication number from DPS API

openapi-specs/activities-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsToNomisIntTest.kt
There were some fairly substantial changes to the appointments part of the activities API. This was to bring the taxonomy in line with the UI. In brief:
- Appointment Occurrence -> Appointment - the event at a specific date, time and location
- Appointment -> Appointment Series - a collection of Appointments on a regular cadence defined by a schedule
- Bulk Appointment -> Appointment Set - a collection of Appointments taking place on the same date and in the same location but at optionally different times
- Appointment Occurrence Allocation -> Appointment Attendee - a prisoner attending a specific appointment
Additionally some key properties have been renamed to match the UI labels or an activities convention:
- appointmentDescription -> customName
- comments -> extraInformation
- created …
=> SAA-1162: Update activities-api-docs.json and related usage

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-incentives-cronjob.yaml, helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-non-associations-cronjob.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsReconciliationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsResource.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsReconciliationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/nonassociations/NonAssociationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NonAssociationsApiMockServer.kt
Relax comparison to ignore dps reason,
decrease the page size to 100,
avoid swapped NA details with same date
=> SDIT-1096 non-association reconciliation process

build.gradle.kts
The build model tasks were never up to date because they shared an output directory and overwrote each other
=> SDIT-1136 Fix openapi generator incremental build

helm_deploy/hmpps-prisoner-to-nomis-update/Chart.yaml, helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `8 => 0 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …
=> Migrating project to use groups in allowlist

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingReconciliationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingReconciliationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingResourceIntTest.kt
DPS is incorrectly returning old adjustments that are no longer relevant, they will fix this - but for now we just filter by bookingId
=> SDIT-1264 Filter DPS adjustments by booking until they fix

openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsReconciliationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsReconciliationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/AdjudicationsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt
A new service, AdjudicationsReconciliationService, has been added to reconcile adjudications between the old and new systems. This includes methods to generate reconciliation reports and check if adjudication punishments match. The Nomis API documentation has also been updated to reflect newly added endpoints related to this service. Corresponding unit tests have been added to ensure the correctness of this service.
=> SDIT-1264 Initial draft of adjudication reconciliation

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsDataRepairResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsDataRepairResourceIntTest.kt
This commit introduces a repair function on the adjudications service that handles punishment resynchronization from the DPS back to NOMIS. This functionality aims to repair data when the domain event adjudication.punishments.updated goes missing. There were also additions to the integration tests to ensure this repair functionality works as expected.
=> SDIT-1458 Add repair functionality to adjudications service

src/main/resources/application.yml
Until we put a proper fix in - call a better endpoint for `/activities/{activityId}` that doesn't return all the schedules.
=> SDIT-1469 Temporarily increase max response size

openapi-specs/nomis-sync-api-docs.json, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsReconciliationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt
DPS Reconciliation API no longer needs a list of prisons to retrieve all adductions for a booking
=> SDIT-1453 Remove prisonIds from NOMIS API getAdaSwardsSummary

helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml
In an attempt to gaurantee it runs after the Activities allocation scheduler.
=> SDIT-1532 Move allocation reconciliation job to first thing in the morning.

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendanceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendanceServiceTest.kt
The activities team are adding a new attendance reason code to distinguish between:
SUSPENDED -> (The prison have chosen to suspend the prisoner from the activity due to poor behaviour for example)
AUTO_SUSPENDED -> (The prisoner has been automatically suspended from the activity due to temporary release from the prison)
This change is to sync the new attendance reason, which is to behave exactly same as SUSPENDED for sync
=> SAA-1592: Sync new attendance reason code

openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsToNomisIntTest.kt
Will try to delete if delete originated from DPS and mapping still exists. 
Will pragmatically ignore delete mapping failures
=> SDIT-1597 Handle `prisoner-alerts.alert-deleted` domain event

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendanceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AllocationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/AttendanceServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/SchedulesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/appointments/AppointmentsServiceTest.kt
They were declared as the wrong type anyway: the occurredAt field is an OffsetDateTime.
=> Remove unused 'occurredAt' message fields

openapi-specs/nomis-sync-api-docs.json, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsReconciliationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsReconciliationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt
If there is an ADA mismatch and there has been a merge since migration and there is an adjudication missing on the active DPS booking then ignore mismatch.
TODO - can make more sophisticated by finding the missing adjudication and find the actual number of ADA days
=> SDIT-1625 Ignore Adjudication mismatch for merges

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsDataRepairResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/PunishmentsToNomisIntTest.kt
`days` is deprecated. Also with the unit measurement is hours set duration to 0 since NOMIS does not understand hours
=> SDIT-1762 Use Adjudication duration rather than days

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsReconciliationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsResourceIntTest.kt
Previously there was bad data in NOMIS where active alerts had expired. This data has been fixed.
Also DPS previously marked alerts that have not started as INACTIVE - this has fixed since it is not consistent with how NOMIS works now
=> SDIT-1730 Alert Reconciliation remove hack

helm_deploy/hmpps-prisoner-to-nomis-update/templates/activities-tidy-mappings-cronjob.yaml
=> SDIT-1803 Kubernetes metadata name has a limit of 52 chars

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsToNomisIntTest.kt
This logic has move the synchronisation from NOMIS where they actual merge takes place
=> SDIT-1836 Remove logic to delete mappings due to a prisoner merge

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/locations/LocationsServiceTest.kt
Fixes MAP-1430: Sync Bug: When changing the working capacity in our service the value is not reflected on NOMIS in the operational capacity. The op cap is always set to the max cap
=> SDIT-1903 Location working capacity does not sync correctly to Nomis

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitToNomisTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/MappingMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt
When the NOMIS API returns a 409 it means the request to create a visit has been rejected due to the visit already existing. The error response will contain the existing NOMIS visit id.
In the is scenario the mapping may have never been created; so use this opportunity to create it now. Else it has been created via a duplicate domain event so nothing more is needed
=> SDIT-2026 Handle visit fails due to a duplicate detected

src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsDataRepairResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsToNomisIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/PunishmentsToNomisIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/AdjudicationsApiMockServer.kt
This makes it easier to change the tests the next time the Adjudication DPS service makes a change to the API
=> SDIT-1772 Convert JSON strings to objects for Wiremock

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/prisonperson/PrisonPersonDomainEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/prisonperson/physicalattributes/PhysicalAttributesSyncService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/prisonperson/physicalattributes/PhysicalAttributesSyncIntTest.kt, src/test/resources/application-test.yml
This handles an edge case where a prisoner is recalled but received on a new booking. When the mistake is noticed the new booking is ended and the prisoner is received again on the correct old booking. If the prisoner was re-measured on the new booking then DPS will have been updated but NOMIS loses this information. Therefore, whenever this happens we know DPS has the most up-to-date measurements so we synchronise from DPS back to NOMIS to keep NOMIS in line.
=> SDIT-2023 Synchronise height and weight from DPS when a prisoner is readmitted on an old booking

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsDataRepairResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsDataRepairResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingAdjustmentsToNomisIntTest.kt
The active status does not by default ever get propagated from DPS to NOMIS.
However, when repairing an adjustment where the status is correct in DPS but not NOMIS we maye wish NOMIS to replicate the DPS status
=> SDIT-2323 Repair can now propagate active status

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDataRepairResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsMappingApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDataRepairResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsMappingApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsMappingApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/alerts/AlertsNomisApiServiceTest.kt
* Gets all alerts in DPS (including inactive)
* Calls NOMIS API that will replace the alerts on the current booking
* Replaces the mappings for that prisoner
=> SDIT-2336 endpoint to repair NOMIS alerts from DPS

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingReconciliationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingReconciliationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/sentencing/SentencingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/services/NomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/wiremock/NomisApiMockServer.kt
Previous this uses the NOMIS api /prisoners/ids using Spring paging. This has now switched the "last id" /bookings/ids method
This should improve performance once we switch the all latest bookings rather than the current active bookings
=> SDIT-2384 Adjustments reconciliation use different paging strategy

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/adjudications/AdjudicationsDataRepairResourceIntTest.kt
Set punishment date to latest hearing date when not present.
Since this repairs a historic adjudication the punishment date would normally be "now" which is when the hearing is entered, but in this case it makes more sense to be the actual date the hearing took place, else a hearing for 10 years ago would have a punishment date of today
=> SDIT-2617 Adjudication repair endpoint.

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/visits/VisitToNomisTest.kt
We have made some minor changes to the `visitComment` and `visitOrderComment` fields to be more accurate. This shorter text also allows us to potentially add additional visit information to the sync for use in NOMIS reports.
Tests have also been updated.
=> Minor tweaks to visitComment and visitOrderComment

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonDpsApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonNomisApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationServiceTest.kt
In NOMIS inactive contacts have little meaning and half of them are created inactive
=> SDIT-2766 Prisoner contact reconciliation now includes inactive contacts

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesReconService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesReconIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesReconTest.kt
We've found that reconciling suspended allocations where the prisoner has been transferred doesn't work out very well as the new prison often ends the allocation in NOMIS, but in practical terms this causes no issues. So now we don't want these to appear on the reconciliation.
On the other hand, we've been ignoring active allocations where the prisoner has been transferred, but again this isn't working out very well because if DPS doesn't end or suspend the allocation then it appears on the DPS prisoner schedule at the new prison which has been confusing staff. So now we do want these to appear on the reconciliation.
I'm starting to wonder if it's time to rewrite the allocation reconciliation. Much has changed in DPS since it was written such as various ways to suspend an allocation and …
=> SDIT-2754 Show bookings in other prisons for allocation reconciliation but not suspended allocation reconciliation

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationServiceTest.kt
DPS allows lower case in names, NOMIS is always converted to upper case
=> SDIT-2771 Ignore person name case in reconciliation

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingDomainEventListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtCasesToNomisIntTest.kt, src/test/resources/application-test.yml
* Does the exact same as a create which is possibly ok, needs some testing
* Small workaround for the domain event not containing the sentence Ids
=> SDIT-2784 Update recall sentences

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtCasesToNomisIntTest.kt
Always set the sentence status to active when updating a recall sentence. TODO - check with DPS if there is ever a scenario a recall sentence in NOMIS should be made inactive
=> SDIT-2782 Recall updated/delete - status

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ContactPersonReconciliationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/ReconciliationLongPagingHelper.kt
SDIT-2778 Refactor to extract channel logic
Extract all Channel and paging logic to ReconciliationLongPagingHelper.kt file.
The helper is typed, though only supports the paging pattern that returns a last ID that will be supplied to retrieve the next page of IDs. That ID is currently hardcoded to Long given NOMIS will typically use a Long when paging via an ID is used.
=> SDIT-2778 Refactor to extract channel logic

helm_deploy/hmpps-prisoner-to-nomis-update/templates/report-court-sentencing-prisoner-cronjob.yaml, helm_deploy/hmpps-prisoner-to-nomis-update/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/config/ResourceServerConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingReconciliationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingReconciliationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingReconciliationResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/courtsentencing/CourtSentencingReconciliationServiceTest.kt
* TODO Use a variation of manualCheckCaseOffenderNo that doesn't build up difference
* TODO move other manual endpoints to Reconciliation resource
* Move shared Channel helper to shared package
=> SDIT-2820 Add court sentencing reconciliation cron

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/batch/BatchManager.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/batch/BatchManagerTest.kt
The previous method (BeanDestroyer) didn't destroy the listener beans until after the application started. In the small amount of time inbetween some messages were [pulled from their queue and processed](https://portal.azure.com#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa5ddf257-3b21-4ba9-a28c-ab30f751b383%2Fresourcegroups%2Fnomisapi-prod-rg%2Fproviders%2Fmicrosoft.operationalinsights%2Fworkspaces%2Fnomisapi-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA3WNsQ6CMBRFd7%252FibcDwyLOmqZIwMBlXww9UeJEm0L60VRY%252FXljcHG%252FOybmdSB%252FtwOnwgXXiyNC7ha%252FsOdrMIzw4r8weynGbeUOlIqWRzqgMkGlIN0QV1DX8E8wuVL98J3IPM998ytYPDG0LxbSIJJToUth%252BMQf0YXEJX7JHMbKEmNHOcxhsdsEnVBdljifSSt76WXwBcWcxKMUAA …
=> SDIT-2804 Remove message listener beans before the application starts

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/batch/BatchManager.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/batch/BatchManagerTest.kt
Currently the application ends gracefully if the batch type is not supported. Change to an enum and the application fails to start, which should cause the cronjob to fail.
Unfortunately I don't think we can create integration tests for failed application starts.
=> SDIT-2804 Fail batch jobs if type is invalid

src/main/resources/application.yml, src/test/resources/application-test.yml
Should solve the issue when an adjustment is updated and deleted at the same time, which results on messages being added to the DLQ until next retry
=> SDIT-3025 Increase errorVisibilityTimeout for adjustments to 1 second

helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesReconService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/personalrelationships/profiledetails/ContactPersonProfileDetailsReconciliationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonertonomisupdate/activities/ActivitiesReconTest.kt
At some point we deliberately designed the reconciliation jobs to be "fire and forget" using `reportScope.launch` so they didn't mess with the main threadpools. I thought an initial `runBlocking` would override this behaviour but no - in long running reconciliations the App is shutting down before the reconciliation finishes.
As these reconciliation jobs are now running in a dedicated Cronjob and have nothing to do with the main pods, we don't care about that any more. The batch jobs can eat all the threads they like.
=> SDIT-2804 Wait for batch jobs to finish, don't fire and forget
